export default {
  testEnvironment: 'node',
  collectCoverageFrom: [
    'src/**/*.js',
    'routes/**/*.js',
    'controllers/**/*.js',
    'models/**/*.js',
    'middleware/**/*.js',
    'utils/**/*.js',
    '!Server.js',
    '!eslint.config.js',
    '!**/*.test.js',
    '!**/node_modules/**',
    '!controllers/AchievementController.js',
    '!controllers/FootprintController.js',
    '!controllers/GameController.js',
    '!controllers/LeaderboardController.js',
    '!controllers/ServiceController.js',
    '!controllers/UserController.js',
    '!middleware/rateLimitMiddleware.js',
    '!middleware/upload.js',
    '!models/Achievement.js',
    '!models/Bill.js',
    '!models/User.js',
    '!routes/achievementRoutes.js',
    '!routes/bill.js',
    '!routes/footprintRoute.js',
    '!routes/gamificationRoute.js',
    '!routes/leaderboardRoutes.js',
    '!routes/userRoute.js',
  ],
  coverageThreshold: {
    global: {
      lines: 80,
      functions: 75,
      branches: 70,
      statements: 80,
    },
    './utils/carbonCalculator.js': {
      lines: 90,
      functions: 90,
      statements: 90,
      branches: 90,
    },
    './controllers/AuthController.js': {
      lines: 80,
      statements: 80,
      functions: 80,
      branches: 75,
    },
  },
  coverageReporters: ['text', 'lcov', 'json-summary'],
  coverageDirectory: 'coverage',
  testTimeout: 15000,
  clearMocks: true,
  restoreMocks: true,
};
